# Generated by Django 4.1.7 on 2023-04-11 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('region', models.CharField(max_length=250, verbose_name='Край/Область/Регион')),
                ('city', models.CharField(max_length=250, verbose_name='Город/Населённый пункт')),
                ('street', models.CharField(max_length=250, verbose_name='Улица/Дом/Квартира')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Телефон')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Почтовый индекс')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('paid', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to='shop.adress', verbose_name='Адрес доставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='product.choices')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.order')),
            ],
            options={
                'verbose_name': 'Товар в заказ',
                'verbose_name_plural': 'Товары в заказах',
                'ordering': ['-id'],
            },
        ),
    ]
