# Generated by Django 4.1.7 on 2023-04-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id'], 'verbose_name': 'Товар в заказ', 'verbose_name_plural': 'Товары в заказах'},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='choices',
        ),
    ]
