# Generated by Django 4.1.7 on 2023-04-05 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_price_choices_price'),
        ('shop', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='choices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='product.choices'),
        ),
    ]
