# Generated by Django 4.1.7 on 2023-04-07 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_orderitem_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('region', models.CharField(max_length=250, verbose_name='Край/Область/Регион')),
                ('city', models.CharField(max_length=250, verbose_name='Город/Населённый пункт')),
                ('street', models.CharField(max_length=250, verbose_name='Улица/Дом/Квартира')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Телефон')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Почтовый индекс')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.order'),
        ),
    ]
