# Generated by Django 4.1.7 on 2023-04-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='choices',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена товара'),
            preserve_default=False,
        ),
    ]
