# Generated by Django 4.1.7 on 2023-04-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='choice_cat',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Название подкатегорий'),
        ),
        migrations.AlterField(
            model_name='product',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='choices', to='product.choices', verbose_name='Разновидности подкатегории'),
        ),
    ]
