# Generated by Django 4.1.7 on 2023-04-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_price_choices_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='article_number',
            field=models.CharField(default=1, max_length=50, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
