# Generated by Django 4.1.7 on 2023-04-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_count_alter_product_choice_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='icon',
        ),
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos', to='product.images', verbose_name='Все видео товара'),
        ),
    ]
