# Generated by Django 4.1.7 on 2023-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_choices_icon_alter_product_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Общие изображения товаров'),
        ),
    ]
