# Generated by Django 4.1.7 on 2023-04-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_videos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos', to='product.videos', verbose_name='Все видео товара'),
        ),
    ]
